### PR TITLE
Make Hasher a distribution suitable for PyPI/pip, rename it to hashes

### PR DESCRIPTION
**Pull request by moreati**
I've packaged the script as a distribution that can be installed with pip.

I had to choose a new name, because [Hasher](https://pypi.python.org/pypi/hasher) is already taken. I went for `hashes`, I hope this is acceptable. The current holder of [hashes](https://pypi.python.org/pypi/hashes) has [agreed to transfer it](https://twitter.com/moreati/status/629695026457636864). I will of course transfer it to you.

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Hey, that looks awesome.  Thanks for sending that over to me.  I'm out on travel right now, but I should be able to look at this in a day or two.

Thanks again!

**Comment by moreati** [comment]
[Jeremy Banks](https://twitter.com/jeremybanks) has very kindly transferred control of https://pypi.python.org/pypi/hashes to me. I can transfer it to you at your request. I'll need your PyPI username.

**Comment by ChrisTruncer** [comment]
Hey there, just wanted to let you know I haven't forgotten about this, just been busy with work and life.  I'll need to create a pypi username, so I'll get that going, and then test this out shortly

**Comment by ChrisTruncer** [comment]
OK, I believe an account should be setup with the username "SonofFlynn"

**Comment by ChrisTruncer** [comment]
Ok, there should be a CTruncer user created now

**Comment by moreati** [comment]
CTruncer is now an owner of https://pypi.python.org/pypi/hashes. You can remove my account once you're happy.

**Comment by ChrisTruncer** [comment]
Hey, so this looks awesome.  My first question is, I've never really made a package for release on Pypi, so what's the best way to test this?

Just download from your repo, install via "python setup.py install", and then run the hashes.py script?  Also, what's the advantages of converting it into this format?

Pardon the noob questions, this would just be the first time for me to have something like this submitted.  Thanks for the help, pull request, and your time!

**Comment by moreati** [comment]
I highly recommend everything the Python Packaging Guide says, including [Uploading your project to PyPI](https://packaging.python.org/en/latest/distributing.html#uploading-your-project-to-pypi).

You can indeed test it with `python setup.py install`. However `pip install .` is better - it will also install dependencies. Use `pip install --user .`, or do everything in a virtualenv to avoid system wide changes.

Once it's installed, you can just run `hashes` - it'll be in your $PATH. That's one advantage of this.

The other advantage is that anyone can install it, straight from PyPI, with `pip install hashes`.

**Comment by ChrisTruncer** [comment]
Hey, so question.  I installed via python setup.py for now (to test the code before pushing to pypi).  I seem to be running into an issue.  When I run "hashes -G --hash-type md5 --plaintext password" it's not outputting anything.  To test to make sure I had the right syntax, I ran the same thing with ./Hasher.py but that did produce the output.  Not sure if it's something I'm doing wrong, or something I need to check out in the code.

**Comment by moreati** [comment]
That's working here. Care to join me on https://appear.in/hashes ? I'll be around at least until 9pm

**Comment by ChrisTruncer** [comment]
Hey,

I prob won’t be able to hop online until about 8PM (East Coast) timeframe.  I’m also on IRC, which might be easier.  I’m on Freenode, you on there by chance?



On August 16, 2015 at 3:26:20 PM, Alex Willmer (notifications@github.com) wrote:

That's working here. Care to join me on https://appear.in/hashes ? I'll be around at least until 9pm

**Comment by moreati** [comment]
Sorry, but no. 8 PM your time is 1 AM my time

**Comment by ChrisTruncer** [comment]
Ha, ah ok.

I'm testing this on a brand new Kali 2.0 install, based off of Debian if that helps. Not sure why, but it isn't running for me. I'll try different hashes later this evening to see if it works any different.

**Comment by moreati** [comment]
Aha, found the problem. If you're outside the source directory when you run `hashes -G --hash-type md5 --plaintext password` it only prints the banner.

**Comment by ChrisTruncer** [comment]
OK, I'll have to look into this then.

**Comment by moreati** [comment]
Did you notice the commit following my comment?

**Comment by ChrisTruncer** [comment]
Ah, I did now.  I missed it when I replied earlier.  I just tested your latest commit and it all works awesome.  Merging this in now, and trying to figure out how to submit to pypi :)

**Comment by ChrisTruncer** [comment]
It's merged in.  So it should be good to go when cloning.  I'm encountering errors uploading it to pypi, so I'll try to figure these out, but this is new to me so I'm not really sure what the issue is at the moment.

**Comment by ChrisTruncer** [comment]
Actually, I think I have it all figured out, so I think this should now be good!

Thanks for the conversion and for helping along with the process!

**Comment by moreati** [comment]
That's great. I have some more ideas/enhancements in the pipe. They'll probably be ready as pull requests next weekish.

**Comment by ChrisTruncer** [comment]
Awesome,

Thanks for your help with this, definitely appreciate it!

**Pull request merged**
